### ISSUE TITLE
严重存在大图缩放显示

### ISSUE THREAD

**Issue by CalmHarbin** [lsqy/taro-music#10]
可以优化图片的尺寸
比如:
https://p2.music.126.net/yRk6kWd00WkJW0T4j92FdA==/109951164261399983.jpg
改为
https://p2.music.126.net/yRk6kWd00WkJW0T4j92FdA==/109951164261399983.jpg?imageView&thumbnail=250x0
就可以得到指定尺寸的图片

**Comment by lsqy** [comment]
多谢提供建议，我抽时间进行下相关优化
