### ISSUE TITLE
可以跑起来  但是没内容

### ISSUE THREAD

**Issue by Ykey12** [lsqy/taro-music#100]
**问题描述**
我使用的cli和项目的依赖包都升级到2.1.4版本了，结果还是报错

**报错信息**
./.temp/app.js
Module build failed (from ./node_modules/@tarojs/webpack-runner/node_modules/babel-loader/lib/index.js):
SyntaxError: E:/workProj/taro-music/.temp/app.js: Unexpected token (126:9)

  124 |         </Provider>;
  125 |   }
> 126 |   config = {
      |          ^
  127 |     pages: ["/pages/index/index", "/pages/dailyRecommend/index", "/pages/my/index", "/pages/videoDetail/index", "/pages/search/index", "/pages/user/index", "/pages/djprogramList
Detail/index", "/pages/searchResult/index",
  128 |     // 'pages/search/index',
  129 |     "/pages/songDetail/index", "/pages/myFans/index", "/pages/myFocus/index", "/pages/myEvents/index", "/pages/login/index", "/pages/playListDetail/index", "/pages/recentPlay/in
dex"],
![image](https://user-images.githubusercontent.com/45032697/79420016-92c9e080-7fea-11ea-8072-a69b4bc1a25e.png)

**系统信息**
"dependencies": {
		"@tarojs/async-await": "2.1.4",
		"@tarojs/cli": "2.1.4",
		"@tarojs/components": "2.1.4",
		"@tarojs/mini-runner": "2.1.4",
		"@tarojs/redux": "2.1.4",
		"@tarojs/redux-h5": "2.1.4",
		"@tarojs/router": "2.1.4",
		"@tarojs/taro": "2.1.4",
		"@tarojs/taro-alipay": "2.1.4",
		"@tarojs/taro-h5": "2.1.4",
		"@tarojs/taro-swan": "2.1.4",
		"@tarojs/taro-tt": "2.1.4",
		"@tarojs/taro-weapp": "2.1.4",
		"classnames": "^2.2.6",
		"nerv-devtools": "^1.5.6",
		"nervjs": "^1.5.6",
		"redux": "^4.0.0",
		"redux-logger": "^3.0.6",
		"redux-thunk": "^2.3.0",
		"taro-ui": "^2.2.2"
	},
	"devDependencies": {
		"@tarojs/plugin-babel": "2.1.4",
		"@tarojs/plugin-csso": "2.1.4",
		"@tarojs/plugin-less": "2.1.4",
		"@tarojs/plugin-sass": "2.1.4",
		"@tarojs/plugin-uglifyjs": "2.1.4",
		"@tarojs/webpack-runner": "2.1.4",
		"@types/react": "^16.4.8",
		"@types/webpack-env": "^1.13.6",
		"babel-eslint": "^8.2.3",
		"babel-plugin-transform-class-properties": "^6.24.1",
		"babel-plugin-transform-decorators-legacy": "^1.3.4",
		"babel-plugin-transform-jsx-stylesheet": "^0.6.5",
		"babel-plugin-transform-object-rest-spread": "^6.26.0",
		"babel-preset-env": "^1.6.1",
		"commitizen": "^4.0.3",
		"cz-conventional-changelog": "^3.0.2",
		"eslint": "^4.19.1",
		"eslint-config-taro": "2.1.4",
		"eslint-plugin-import": "^2.12.0",
		"eslint-plugin-react": "^7.8.2",
		"eslint-plugin-taro": "2.1.4",
		"eslint-plugin-typescript": "^0.12.0",
		"husky": "^3.1.0",
		"typescript": "^3.0.1"
	},
taro info
� Taro v2.1.4

  Taro CLI 2.1.4 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 12.13.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.21.1 - C:\Users\yk\AppData\Roaming\npm\yarn.CMD
      npm: 6.13.2 - C:\Program Files\nodejs\npm.CMD

**Comment by yimiIO** [comment]
same same

**Comment by lsqy** [comment]
注意目前只支持小程序平台，所以注意要执行`npm run dev:weapp`,看你的错误是不是因为执行`npm run dev:h5`导致的
