### ISSUE TITLE
不支持H5么， 报错如下， 小程序 Ok

### ISSUE THREAD

**Issue by yimiIO** [lsqy/taro-music#101]
Failed to compile.

./.temp/app.js
Module build failed (from ./node_modules/babel-loader/lib/index.js):
SyntaxError: Unexpected token (126:9)

  124 |         </Provider>;
  125 |   }
> 126 |   config = {
      |          ^
  127 |     pages: ["/pages/index/index", "/pages/dailyRecommend/index", "/pages/my/index", "/pages/videoDetail/index", "/pages/search/index", "/pages/user/index", "/pages/djprogramListDetail/index", "/pages/searchResult/index",
  128 |     // 'pages/search/index',
  129 |     "/pages/songDetail/index", "/pages/myFans/index", "/pages/myFocus/index", "/pages/myEvents/index", "/pages/login/index", "/pages/playListDetail/index", "/pages/recentPlay/index"],

taro-music git:(master) ✗ taro info
👽 Taro v2.1.5

  Taro CLI 2.1.5 environment info:
    System:
      OS: macOS 10.15.1
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 13.6.0 - ~/.nvm/versions/node/v13.6.0/bin/node
      npm: 6.13.4 - ~/.nvm/versions/node/v13.6.0/bin/npm
    npmPackages:
      @tarojs/async-await: 2.1.5 => 2.1.5 
      @tarojs/components: 2.1.5 => 2.1.5 
      @tarojs/mini-runner: 2.1.5 => 2.1.5 
      @tarojs/plugin-babel: 2.1.5 => 2.1.5 
      @tarojs/plugin-csso: 2.1.5 => 2.1.5 
      @tarojs/plugin-less: 2.1.5 => 2.1.5 
      @tarojs/plugin-sass: 2.1.5 => 2.1.5 
      @tarojs/plugin-uglifyjs: 2.1.5 => 2.1.5 
      @tarojs/redux: 2.1.5 => 2.1.5 
      @tarojs/redux-h5: 2.1.5 => 2.1.5 
      @tarojs/router: 2.1.5 => 2.1.5 
      @tarojs/taro: 2.1.5 => 2.1.5 
      @tarojs/taro-alipay: 2.1.5 => 2.1.5 
      @tarojs/taro-h5: 2.1.5 => 2.1.5 
      @tarojs/taro-swan: 2.1.5 => 2.1.5 
      @tarojs/taro-tt: 2.1.5 => 2.1.5 
      @tarojs/taro-weapp: 2.1.5 => 2.1.5 
      @tarojs/webpack-runner: 2.1.5 => 2.1.5 
      eslint-config-taro: 2.1.5 => 2.1.5 
      eslint-plugin-taro: 2.1.5 => 2.1.5 
      nerv-devtools: ^1.5.6 => 1.5.6 
      nervjs: ^1.5.6 => 1.5.6 
      taro-ui: ^2.2.2 => 2.3.3

**Comment by lsqy** [comment]
目前是只支持小程序版本，H5的适配需要以后再进行开展，敬请期待
