### ISSUE TITLE
支付宝小程序报错

### ISSUE THREAD

**Issue by shy19940217** [lsqy/taro-music#104]
<img width="826" alt="屏幕快照 2020-04-20 下午4 21 17" src="https://user-images.githubusercontent.com/20577803/79730463-76e47880-8323-11ea-95ed-abe13fdc2741.png">

**Comment by lsqy** [comment]
目前主要是适配的微信小程序端，支付宝端路由跳转跟微信小程序有一些不一致，后期有时间了会加上相应适配处理
