### ISSUE TITLE
yarn dev:weapp时提示 items.forEach is not a function

### ISSUE THREAD

**Issue by yangzqv** [lsqy/taro-music#108]
(node:23561) UnhandledPromiseRejectionWarning: TypeError: items.forEach is not a function
    at /usr/local/lib/node_modules/@tarojs/cli/node_modules/_@tarojs_service@2.2.3@@tarojs/service/dist/utils/index.js:17:15
    at /usr/local/lib/node_modules/@tarojs/cli/node_modules/_@tarojs_service@2.2.3@@tarojs/service/dist/utils/index.js:33:51
    at Kernel.initPresetsAndPlugins (/usr/local/lib/node_modules/@tarojs/cli/node_modules/_@tarojs_service@2.2.3@@tarojs/service/dist/Kernel.js:72:107)
    at Kernel.<anonymous> (/usr/local/lib/node_modules/@tarojs/cli/node_modules/_@tarojs_service@2.2.3@@tarojs/service/dist/Kernel.js:40:18)
    at Generator.next (<anonymous>)
    at /usr/local/lib/node_modules/@tarojs/cli/node_modules/_@tarojs_service@2.2.3@@tarojs/service/dist/Kernel.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/usr/local/lib/node_modules/@tarojs/cli/node_modules/_@tarojs_service@2.2.3@@tarojs/service/dist/Kernel.js:4:12)
    at Kernel.init (/usr/local/lib/node_modules/@tarojs/cli/node_modules/_@tarojs_service@2.2.3@@tarojs/service/dist/Kernel.js:36:16)
    at Kernel.<anonymous> (/usr/local/lib/node_modules/@tarojs/cli/node_modules/_@tarojs_service@2.2.3@@tarojs/service/dist/Kernel.js:239:24)
(node:23561) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:23561) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by lsqy** [comment]
先确认下你的`taro-cli`的版本与项目中`taro`的版本是否保持一致

**Comment by yangzqv** [comment]
大佬，不一致，我的是最新版本的。

**Comment by lsqy** [comment]
那可以通过执行`taro update self`(`mac`或者`linux`前面需要加上`sudo`)以及`taro update project`进行`cli`与项目依赖的更新保持一致，否则将会导致项目无法正常运行

**Comment by 120764482** [comment]
yarn dev:weapp时提示Taro 配置有误，请检查！  [✗] plugins 应该为数组类型，版本确认一致

**Comment by 120764482** [comment]
npm run dev:h5 时报错
�   Failed to compile.

./.temp/app.js
Module build failed (from ./node_modules/@tarojs/webpack-runner/node_modules/babel-loader/lib/index.js):
SyntaxError: C:/Users/Administrator/Desktop/taro-music/.temp/app.js: Unexpected token (126:9)

  124 |         </Provider>;
  125 |   }
> 126 |   config = {
      |          ^
  127 |     pages: ["/pages/index/index", "/pages/dailyRecommend/index", "/pages/my/index", "/pages/videoDetail/index", "/pages/search/index", "/pages/user/index", "/pages/djprogramListDetail/index", "/pages/searchResult/index",
  128 |     // 'pages/search/index',
  129 |     "/pages/songDetail/index", "/pages/myFans/index", "/pages/myFocus/index", "/pages/myEvents/index", "/pages/login/index", "/pages/playListDetail/index", "/pages/recentPlay/index"],

**Comment by mullex** [comment]
> npm run dev：h5时报错
> 编译失败。
> 
> ./.temp/app.js
> 模块构建失败（来自./node_modules/@tarojs/webpack-runner/node_modules/babel-loader/lib/index.js）：语法错误
> ：C：/ Users / Administrator / Desktop / taro-音乐/.temp/app.js：意外令牌（126：9）
> 
> 124 | ;
> 125 | }
> 
> > 126 | config = { 
> > | ^ 
> > 127 | 网页：[“ / pages / index / index”，“ / pages / dailyRecommend / index”，“ / pages / my / index”，“ / pages / videoDetail / index”，“ / pages / search / index”，“ /页面/用户/索引”，“ / pages / djprogramListDetail /索引”，“ / pages / searchResult / index”，
> > 128 | //'pages / search / index'，
> > 129 | “ / pages / songDetail / index”，“ / pages / myFans / index”，“ / pages / myFocus / index”，“ / pages / myEvents / index”，“ / pages / login / index”，“ / pages / playListDetail” / index“，” / pages / recentPlay / index“]，

有可能是你的babel没有配置生效，检查config/index中，配置项是否存在：
config = {
  babel: {
    sourceMap: true,
    presets: [
      [
        "env",
        {
          modules: false
        }
      ]
    ],
    plugins: [
      "transform-decorators-legacy",
      "transform-class-properties",
      "transform-object-rest-spread"
    ]
  },
  plugins: [
    "@tarojs/plugin-sass"
  ]
}

**Comment by mitayou** [comment]
> npm run dev:h5 时报错
> �   Failed to compile.
> ./.temp/app.js
> Module build failed (from ./node_modules/@tarojs/webpack-runner/node_modules/babel-loader/lib/index.js):
> SyntaxError: C:/Users/Administrator/Desktop/taro-music/.temp/app.js: Unexpected token (126:9)
> 124 |         ;
> 125 |   }
> 
> 126 |   config = {
> |          ^
> 127 |     pages: ["/pages/index/index", "/pages/dailyRecommend/index", "/pages/my/index", "/pages/videoDetail/index", "/pages/search/index", "/pages/user/index", "/pages/djprogramListDetail/index", "/pages/searchResult/index",
> 128 |     // 'pages/search/index',
> 129 |     "/pages/songDetail/index", "/pages/myFans/index", "/pages/myFocus/index", "/pages/myEvents/index", "/pages/login/index", "/pages/playListDetail/index", "/pages/recentPlay/index"],

检查你的babel配置项是否存在：
config = {
  babel: {
    sourceMap: true,
    presets: [
      [
        "env",
        {
          modules: false
        }
      ]
    ],
    plugins: [
      "transform-decorators-legacy",
      "transform-class-properties",
      "transform-object-rest-spread"
    ]
  },
  plugins: [
    "@tarojs/plugin-sass"
  ]
}

**Comment by mitayou** [comment]
> npm run dev:h5 时报错
> �   Failed to compile.
> ./.temp/app.js
> Module build failed (from ./node_modules/@tarojs/webpack-runner/node_modules/babel-loader/lib/index.js):
> SyntaxError: C:/Users/Administrator/Desktop/taro-music/.temp/app.js: Unexpected token (126:9)
> 124 |         ;
> 125 |   }
> 
> 126 |   config = {
> |          ^
> 127 |     pages: ["/pages/index/index", "/pages/dailyRecommend/index", "/pages/my/index", "/pages/videoDetail/index", "/pages/search/index", "/pages/user/index", "/pages/djprogramListDetail/index", "/pages/searchResult/index",
> 128 |     // 'pages/search/index',
> 129 |     "/pages/songDetail/index", "/pages/myFans/index", "/pages/myFocus/index", "/pages/myEvents/index", "/pages/login/index", "/pages/playListDetail/index", "/pages/recentPlay/index"],

打开config/index.js，检查babel配置项是否存在：
```js
config = {
  babel: {
    sourceMap: true,
    presets: [
      [
        "env",
        {
          modules: false
        }
      ]
    ],
    plugins: [
      "transform-decorators-legacy",
      "transform-class-properties",
      "transform-object-rest-spread"
    ]
  },
  plugins: [
    "@tarojs/plugin-sass"
  ]
}
```
