### ISSUE TITLE
手机号登陆

### ISSUE THREAD

**Issue by chaojiangcn** [lsqy/taro-music#11]
谁能告诉我怎么登录进去？_QQ_

**Comment by lsqy** [comment]
目前只支持手机号进行登录

**Comment by chaojiangcn** [comment]
嗯 手机号怎么登陆进去呢   输入手机号  然后密码是_？_

**Comment by lsqy** [comment]
密码就是你自己的网易云音乐密码，你可以用自己的手机号申请一个网易云的帐号 @chaojiangcn

**Comment by chaojiangcn** [comment]
> 目前只支持手机号进行登录



> 密码就是你自己的网易云音乐密码，你可以用自己的手机号申请一个网易云的帐号 @chaojiangcn

好的，跟着学习了
