### ISSUE TITLE
sass  无法编译1q

### ISSUE THREAD

**Issue by dt1109** [lsqy/taro-music#112]
当前项目使用了 sass，请安装插件 @tarojs/plugin-sass，并且在 plugins 中进行配置，否则将无法编译 sass 文件！
参考文档：https://nervjs.github.io/taro/docs/config-detail#plugins
请问这个sass plugin具体怎么配置啊 我配置的一直无法编译

**Comment by lsqy** [comment]
为什么不用`scss`呢

**Comment by LiuDoo** [comment]
试试用下面的代码替换config/index.js中的代码，也许能够解决你的问题

const config = {
  projectName: 'test',
  date: '2020-6-20',
  designWidth: 750,
  deviceRatio: {
    '640': 2.34 / 2,
    '750': 1,
    '828': 1.81 / 2
  },
  sourceRoot: 'src',
  outputRoot: 'dist',
  babel: {
    sourceMap: true,
    presets: [
      ['env', {
        modules: false
      }]
    ],
    plugins: [
      'transform-decorators-legacy',
      'transform-class-properties',
      'transform-object-rest-spread',
    ]
  },
  plugins: [
    '@tarojs/plugin-sass',
    
  ],
  defineConstants: {
  },
  mini: {
    postcss: {
      pxtransform: {
        enable: true,
        config: {}
      },
      url: {
        enable: true,
        config: {
          limit: 10240 // 设定转换尺寸上限
        }
      },
      cssModules: {
        enable: false, // 默认为 false，如需使用 css modules 功能，则设为 true
        config: {
          namingPattern: 'module', // 转换模式，取值为 global/module
          generateScopedName: '[name]__[local]___[hash:base64:5]'
        }
      }
    }
  },
  h5: {
    publicPath: '/',
    staticDirectory: 'static',
    postcss: {
      autoprefixer: {
        enable: true,
        config: {
          browsers: [
            'last 3 versions',
            'Android >= 4.1',
            'ios >= 8'
          ]
        }
      },
      cssModules: {
        enable: false, // 默认为 false，如需使用 css modules 功能，则设为 true
        config: {
          namingPattern: 'module', // 转换模式，取值为 global/module
          generateScopedName: '[name]__[local]___[hash:base64:5]'
        }
      }
    }
  }
}

module.exports = function (merge) {
  if (process.env.NODE_ENV === 'development') {
    return merge({}, config, require('./dev'))
  }
  return merge({}, config, require('./prod'))
}

**Comment by mitayou** [comment]
解决方案
```
// 打开config/index.js
config: {
  // 增加此项
  plugins: [
    "@tarojs/plugin-sass"
  ]
}
```
注意：
1. 与上下文保持一致使用双引号
2. 旧版本的项目可能如下所示
> 方案：将babel与plugin分离
```
// 修改前
config: {
    plugins: {
        babel: {
            sourceMap: true,
            presets: [
              [
                "env",
                {
                  modules: false
                }
              ]
            ],
            plugins: [
              "transform-decorators-legacy",
              "transform-class-properties",
              "transform-object-rest-spread"
            ]
        }
    }
}

```
可能会存在plugins已存在的情况，可以修改为
```
// 修改后：
config = {
  babel: {
    sourceMap: true,
    presets: [
      [
        "env",
        {
          modules: false
        }
      ]
    ],
    plugins: [
      "transform-decorators-legacy",
      "transform-class-properties",
      "transform-object-rest-spread"
    ]
  },
  plugins: [
    "@tarojs/plugin-sass"
  ]
}
```

**Comment by dt1109** [comment]
Ok thankful



---原始邮件---
发件人: "supet151"<notifications@github.com&gt;
发送时间: 2020年6月23日(周二) 下午5:06
收件人: "lsqy/taro-music"<taro-music@noreply.github.com&gt;;
抄送: "Author"<author@noreply.github.com&gt;;"dt1109"<1147624935@qq.com&gt;;
主题: Re: [lsqy/taro-music] sass  无法编译1q (#112)




 
试试用下面的代码替换config/index.js中的代码，也许能够解决你的问题
 
const config = {
 projectName: 'test',
 date: '2020-6-20',
 designWidth: 750,
 deviceRatio: {
 '640': 2.34 / 2,
 '750': 1,
 '828': 1.81 / 2
 },
 sourceRoot: 'src',
 outputRoot: 'dist',
 babel: {
 sourceMap: true,
 presets: [
 ['env', {
 modules: false
 }]
 ],
 plugins: [
 'transform-decorators-legacy',
 'transform-class-properties',
 'transform-object-rest-spread',
 ]
 },
 plugins: [
 '@tarojs/plugin-sass',
 
],
 defineConstants: {
 },
 mini: {
 postcss: {
 pxtransform: {
 enable: true,
 config: {}
 },
 url: {
 enable: true,
 config: {
 limit: 10240 // 设定转换尺寸上限
 }
 },
 cssModules: {
 enable: false, // 默认为 false，如需使用 css modules 功能，则设为 true
 config: {
 namingPattern: 'module', // 转换模式，取值为 global/module
 generateScopedName: '[name][local][hash:base64:5]'
 }
 }
 }
 },
 h5: {
 publicPath: '/',
 staticDirectory: 'static',
 postcss: {
 autoprefixer: {
 enable: true,
 config: {
 browsers: [
 'last 3 versions',
 'Android &gt;= 4.1',
 'ios &gt;= 8'
 ]
 }
 },
 cssModules: {
 enable: false, // 默认为 false，如需使用 css modules 功能，则设为 true
 config: {
 namingPattern: 'module', // 转换模式，取值为 global/module
 generateScopedName: '[name][local]__[hash:base64:5]'
 }
 }
 }
 }
 }
 
module.exports = function (merge) {
 if (process.env.NODE_ENV === 'development') {
 return merge({}, config, require('./dev'))
 }
 return merge({}, config, require('./prod'))
 }

**Comment by lsqy** [comment]
为各位小伙伴主动提供解决方案点赞，那这个`issue`我这边就先关掉了～
