### ISSUE TITLE
运行 npm run dev:webapp 报 Cannot find module 'lodash/fp'，试了n种办法都不行，求助！

### ISSUE THREAD

**Issue by fzp0723** [lsqy/taro-music#115]
![image](https://user-images.githubusercontent.com/11917690/86916324-0432ae80-c156-11ea-8158-0ff5c7c5779d.png)
![image](https://user-images.githubusercontent.com/11917690/86916354-101e7080-c156-11ea-9092-1af00aa05ffb.png)

**Comment by fzp0723** [comment]
哭了，想看个界面都看不到。

**Comment by lsqy** [comment]
@Paul0523 稍等，我这边定位下你这个问题的原因

**Comment by lsqy** [comment]
我这边在本地试了下重新安装依赖，确实也遇到了这个问题，应该试taro-cli官方更新有些问题，等后续官方更新了再尝试下，有消息了我也会同步一下你 @Paul0523 ，你也可以在这个论坛上跟进下这个问题 [http://taro-club.jd.com/topic/1746/taro-init-error-cannot-find-module-lodash-fp](http://taro-club.jd.com/topic/1746/taro-init-error-cannot-find-module-lodash-fp)

**Comment by fzp0723** [comment]
@lsqy 好的，感谢~

**Comment by fzp0723** [comment]
看论坛已经修复了，感谢~  手动 yarn add lodash@4.17.19 下就行了
