### ISSUE TITLE
npm run dev:h5报错

### ISSUE THREAD

**Issue by ZhengXingchi** [lsqy/taro-music#118]
**问题描述**
`npm run dev:h5报错 `

**报错信息**

```
./.temp/app.js
Module build failed (from ./node_modules/@tarojs/webpack-runner/node_modules/babel-loader/lib/index.js):
SyntaxError: Unexpected token (126:9)

  124 |         </Provider>;
  125 |   }
> 126 |   config = {
      |          ^
  127 |     pages: ["/pages/index/index", "/pages/dailyRecommend/index", "/pages/my/index", "/page
```

**系统信息**
`taro v2.1.5`

**Comment by lsqy** [comment]
应该是`@tarojs/cli`的版本不一致导致的，可以执行下方命令之后再看下 @ZhengXingchi
```
  如果之前有安装其他版本的@tarojs/cli，需要先全局卸载，执行下方命令,执行完后再执行下方两步
  npm uninstall -g @tarojs/cli
  rm -rf node_modules
  ---------------
  第一步
  npm install -g @tarojs/cli@2.1.5
  or
  cnpm install -g @tarojs/cli@2.1.5
  or
  yarn global add @tarojs/cli@2.1.5

  第二步
  npm install
  or
  cnpm install
  or
  yarn
```

**Comment by hms58** [comment]
![image](https://user-images.githubusercontent.com/7508625/88502008-cb248600-cfff-11ea-980a-aa4115407805.png)

我的也是这样，装的是2.1.5

**Comment by lsqy** [comment]
请按上方我的评论步骤执行一下@hms58 这个是`@tarojs/cli`不一致导致的，现在默认安装的`@tarojs/cli`是3.x的

**Comment by ZhengXingchi** [comment]
@hms58  后来我把项目非业务代码抽离出来，改造了一下，使用了@tarojs/cli的3.0.5版本，目前已经应用于公司业务，所以这个issue也没有考证什么原因引起的了，此就结贴了，感谢作者的分享。

**Comment by lsqy** [comment]
> @hms58 后来我把项目非业务代码抽离出来，改造了一下，使用了@tarojs/cli的3.0.5版本，目前已经应用于公司业务，所以这个issue也没有考证什么原因引起的了，此就结贴了，感谢作者的分享。
赞
