### ISSUE TITLE
用h5环境时出错，把babel移出plugins: { } 就好了。

### ISSUE THREAD

**Issue by 9590** [lsqy/taro-music#124]
用h5环境时( npm run dev:weapp）时会编译出错，

把babel移出plugins: { } 就好了。

babel: {
      sourceMap: true,
      presets: [
        [
          "env",
          {
            modules: false
          }
        ]
      ],
      plugins: [
        "transform-decorators-legacy",
        "transform-class-properties",
        "transform-object-rest-spread"
      ]
    },  

  plugins: {

  },

**Comment by lsqy** [comment]
使用的`taro`版本是多少呢？

**Comment by 9590** [comment]
2.x
