### ISSUE TITLE
项目没跑起来，求助！

### ISSUE THREAD

**Issue by LijiaHou** [lsqy/taro-music#125]
你好，我在按照文档把后端和前端的依赖安装好，然后最后执行

`npm run dev:weapp`

时出现

> ➜  taro-music git:(master) ✗ npm run dev:weapp
> 
> > taro-music@1.0.5 dev:weapp
> > npm run build:weapp -- --watch
> 
> 
> > taro-music@1.0.5 build:weapp
> > taro build --type weapp "--watch"
> 
> 👽 Taro v3.0.24
> 
> 请在项目配置中设置 framework 字段：https://taro-docs.jd.com/taro/docs/config

这种报错，求问怎么解决呢~

**Comment by lsqy** [comment]
目前还没有适配`taro3.0`，所以需要按照`README`中使用`2.1.5`版本的

**Comment by LijiaHou** [comment]
> 目前还没有适配`taro3.0`，所以需要按照`README`中使用`2.1.5`版本的

原来是这样，谢谢回复，没有注意版本的问题-_-
