### ISSUE TITLE
求助，运行失败，taro cli 版本 2.1.5

### ISSUE THREAD

**Issue by capy9** [lsqy/taro-music#127]
UnhandledPromiseRejectionWarning: Error: Cannot find module 'babel-preset-taro' from

**Comment by capy9** [comment]
yarn add babel-preset-taro

**Comment by lsqy** [comment]
> yarn add babel-preset-taro

执行完后可以了吗 @capy9

**Comment by capy9** [comment]
还是不行

**Comment by deepocean1226** [comment]
你改东西了吗？我npm install后就正常可以跑了

**Comment by lsqy** [comment]
@capy9 你重新拉一下项目，然后确保按照`README`文档中的操作步骤试一下
