### ISSUE TITLE
用户登录bug反馈

### ISSUE THREAD

**Issue by deepocean1226** [lsqy/taro-music#128]
**问题描述**

正常搭建环境，运行项目推荐的网易云api服务后。在“我的”界面跳转登录页，正确登录后重新点击“我的”界面后又重新跳转到登录页，无法返回。
排查后发现是my.index的getSubcount响应失败导致本地存储的用户信息被删。

**复现步骤**
没有特殊操作，copy了别的小伙伴的步骤
1、git clone https://github.com/Binaryify/NeteaseCloudMusicApi.git
cd NeteaseCloudMusicApi
cnpm i
npm run start
2、git clone https://github.com/lsqy/taro-music.git
cd taro-music
cnpm install -g @tarojs/cli@2.1.5
cnpm i
修改 project.config.json 中的appid为自己的测试id
cd src
创建config.ts文件 内容为：export const baseUrl: string = 'http://自己服务器ip:3000'(已测试该服务都可正常使用)
npm run dev:weapp
3、在微信开发者工具打开 dist 目录中的小程序项目

4、问题代码所在
```js
// pages/my/index.ts

  componentDidShow() {
    if (!this.state.userInfo) {
      Taro.navigateTo({
        url: "/pages/login/index"
      });
      return;
    }
    // this.getSubcount();  出错的代码（看了下内容无实质作用），注释掉后可以正常使用
    this.getUserDetail();
    this.getPlayList();
  }
```

**期望行为**
正常登录后重新进入“我的”页面能显示用户信息。

**报错信息**
![image](https://user-images.githubusercontent.com/37998002/120782380-87be7080-c55c-11eb-97f2-4a78a87e2d32.png)

**系统信息**
![image](https://user-images.githubusercontent.com/37998002/120782525-ade41080-c55c-11eb-9537-dc25c69c61e7.png)

**补充信息**
问题就是getSubcount()这个请求的权限显示未登录，把本地storage全删了！不清楚作者该函数用意。
api.ts内
![image](https://user-images.githubusercontent.com/37998002/120783164-53977f80-c55d-11eb-991d-83d791ed9fe9.png)

**Comment by lsqy** [comment]
@deepocean1226 getSubcount这个接口是为了获取用户信息 , 歌单，收藏，mv, dj 数量用的，这部分的相应逻辑以及视图层还未开展，现在的问题其实是登陆态没有维持，这边修复下

**Comment by lsqy** [comment]
@deepocean1226 该问题已解决，可以pull一下最新的`master`分支代码即可,感谢反馈问题～

**Comment by deepocean1226** [comment]
> @deepocean1226 该问题已解决，可以pull一下最新的`master`分支代码即可,感谢反馈问题～

okok，感谢作者，项目学习用很好！

**Comment by lsqy** [comment]
@deepocean1226 多多交流
