### ISSUE TITLE
跑不起来

### ISSUE THREAD

**Issue by Smlie-max** [lsqy/taro-music#131]
![微信截图_20210615192607](https://user-images.githubusercontent.com/52807074/122044830-8e2bd280-ce0f-11eb-9915-8273732f0180.png)

**Comment by lsqy** [comment]
检查下自己的taro版本是否正确

**Comment by luowhsd** [comment]
我发现要npm才行，cnpm和yarn都不行

**Comment by Smlie-max** [comment]
taro版本是3.2.12，要什么版本???

**Comment by lsqy** [comment]
@Smlie-max README注意事项中有说明，需要是2.1.5,目前该项目于taro3.0不兼容，可以按照README中进行操作

**Comment by Smlie-max** [comment]
@lsqy 我看你标题写着从taro2.0升级3.0的

**Comment by Smlie-max** [comment]
@lsqy 不好意思，看错了
