### ISSUE TITLE
运行 npm run dev:h5  编译错误

### ISSUE THREAD

**Issue by 343512292** [lsqy/taro-music#132]
`
🙅   Failed to compile.

./.temp/app.js
Module build failed (from ./node_modules/@tarojs/webpack-runner/node_modules/babel-loader/lib/index.js):
SyntaxError: D:/taro-music/.temp/app.js: Unexpected token (125:9)
   \</Provider\>;
}
config = {
          ^
pages: ["/pages/index/index", "/pages/dailyRecommend/index", "/pages/my/index", "/pages/videoDetail/index", "/pages/search/index", "/pages/user/index", "/pages/djprogramListDetail/index", "/pages/searchResult/index",
// 'pages/search/index',
"/pages/songDetail/index", "/pages/myFans/index", "/pages/myFocus/index", "/pages/myEvents/index", "/pages/login/index", "/pages/playListDetail/index", "/pages/recentPlay/index"],

`

不知道是什么原因 ！

**Comment by lsqy** [comment]
@343512292 先按照README文档确认下自己的taro版本是否正确

**Comment by lsqy** [comment]
与上方`issue`一致，close这个
