### ISSUE TITLE
npm run dev:weapp 编译失败

### ISSUE THREAD

**Issue by 343512292** [lsqy/taro-music#133]
`
- 即将开始启动编译，请稍等~TypeError: unknown: Duplicate declaration "Taro"
  1 | import Taro, { internal_safe_get, internal_get_original, internal_inline_style, handleLoopRef, genCompid, genLoopCompid, propsManager } from "@tarojs/taro-weapp";
  2 | import "@tarojs/async-await";
> 3 | import Taro, { Component as __BaseComponent } from "@/tarojs/taro";
    | ----------        ^
  4 | import { setStore, ReduxContext } from "@tarojs/redux";
  5 | 
  6 | import configStore from "./store/index";

`

**Comment by lsqy** [comment]
@343512292 先按照README文档确认下自己的taro版本是否正确

**Comment by 343512292** [comment]
D:\taro-music>taro -V
👽 Taro v2.1.5

2.1.5

重新安装后 还是报同样的错误！ @lsqy

**Comment by 343512292** [comment]
npm run dev:h5
提示
`
./.temp/app.js
Module build failed (from ./node_modules/@tarojs/webpack-runner/node_modules/babel-loader/lib/index.js):
SyntaxError: D:/taro-music/.temp/app.js: Unexpected token (125:9)

`
@lsqy

**Comment by lsqy** [comment]
@343512292 重新安装后执行下将`node_modules`删除后重新安装,执行下`npm install`

**Comment by lsqy** [comment]
@343512292 目前h5的方式是存在问题，主要是在微信小程序上进行运行，播放音乐之类的用的是微信小程序的相关接口能力

**Comment by 343512292** [comment]
![图片](https://user-images.githubusercontent.com/22487931/129501402-5c25bf4d-7a8b-450c-9f6d-a771f815a18d.png)
不知道为什么？node_modulse 依赖中的文件报错

**Comment by 343512292** [comment]
找到原因了  
不知道为什么 本地文件  tpp.tsx  中 import Taro, { Component, Config } from "@/tarojs/taro";    引入地址莫名其妙多带了个 **”/“**
问题解决了！
感谢大神！

**Comment by lsqy** [comment]
有可能是`windows`环境莫名新增的，解决了就好，那这边就把这个`issue`关闭了
