### ISSUE TITLE
npm install 错误

### ISSUE THREAD

**Issue by WilliamJJXue** [lsqy/taro-music#135]
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! Found: eslint@4.19.1
npm ERR! node_modules/eslint
npm ERR!   dev eslint@"^4.19.1" from the root project
npm ERR!   peer eslint@"^2 || ^3 || ^4 || ^5 || ^6 || ^7.2.0" from eslint-plugin-import@2.24.1
npm ERR!   node_modules/eslint-plugin-import
npm ERR!     dev eslint-plugin-import@"^2.12.0" from the root project
npm ERR!   3 more (eslint-plugin-react, eslint-config-taro, eslint-plugin-taro)
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer eslint@"^5.0.0 || ^6.0.0" from @typescript-eslint/parser@2.34.0
npm ERR! node_modules/eslint-config-taro/node_modules/@typescript-eslint/parser
npm ERR!   @typescript-eslint/parser@"^2.x" from eslint-config-taro@3.0.3
npm ERR!   node_modules/eslint-config-taro
npm ERR!     dev eslint-config-taro@"3.0.3" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /Users/william/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/william/.npm/_logs/2021-08-24T02_44_48_929Z-debug.log

feature_upgrade_taro3.0分支问题

**Comment by lsqy** [comment]
@WilliamJJXue feature_upgrade_taro3.0分支目前还不具备可以run起来的条件，暂时还没有时间去关注这块，建议不要去看这个分支
