### ISSUE TITLE
未分包，导致无法预览

### ISSUE THREAD

**Issue by nanhupatar** [lsqy/taro-music#137]
**问题描述**

**复现步骤**

```js
// 这里可以贴代码
```

**期望行为**

**报错信息**

**系统信息**

**补充信息**

**Comment by nanhupatar** [comment]
Error: 代码包大小为 2056 kb，上限为 2048 kb，请删除文件后重试 。可以做一下分包--

**Comment by lsqy** [comment]
感谢反馈，分包会近期开展优化下 @nanhupatar
