### ISSUE TITLE
项目无法保持登录状态，点击“我的”标签页每次都会要求登录

### ISSUE THREAD

**Issue by AvailableForTheWorld** [lsqy/taro-music#138]
**问题描述**

开发者您好，我在微信开发者工具中打开项目后无法保持登录状态，即每次点击“我的”标签页都需要重新登录，

**复现步骤**

打开微信开发者工具后弹出项目内容，自动弹出登录框，填写正确的用户名密码登陆后进入首页，但是我想要进入我的标签页，每次点击又要重新输入用户名和密码了

```js
// 这里可以贴代码
```

**期望行为**

希望能够保持登录，能够查看我的标签页状态
**报错信息**

![image](https://user-images.githubusercontent.com/49779788/144217076-cedf254f-ef93-488b-9ace-df3f5a19861d.png)

**系统信息**

最新版本：Taro v3.3.15
报错平台：[weapp]

**补充信息**

**Comment by lsqy** [comment]
@AvailableForTheWorld 可以重启下你的接口服务，以及清除下微信小程序的缓存试一下，这个问题是因为cookie没有验证通过导致的

**Comment by AvailableForTheWorld** [comment]
您好，我重启了也清理了缓存，然后看后端控制台打印的结果如下，状态码是301？为啥，是不是因为最新版taro v3.3.15还不怎么兼容

[OK] /login/cellphone?phone=***********&password=***************
[ERR] /user/subcount { status: 301, body: { code: 301 } }
[OK] /user/playlist?uid=*********&limit=300
[OK] /user/detail?uid=*********
[ERR] /user/subcount { status: 301, body: { code: 301 } }
[ERR] /user/subcount { status: 301, body: { code: 301 } }

**Comment by lsqy** [comment]
优化了下cookie的逻辑，有时间可以拉下master再看下 @AvailableForTheWorld

**Comment by AvailableForTheWorld** [comment]
我今天更新了，发现问题仍然存在：即我每点我的navBar的话它会自动清空我的Storage中的cookie，看起来好像是每次点pages 中的my它都会清空cookie然后需要重新登录

**Comment by lsqy** [comment]
清除下开发者工具的缓存，另外node的服务可以换一个端口后再试下看看，我这边试了是可以的 @AvailableForTheWorld

**Comment by AvailableForTheWorld** [comment]
我按照您说的做，但还是不能work
可能是我版本问题了
我用的是taro 3.3.15
