### ISSUE TITLE
你好，请教一个问题

### ISSUE THREAD

**Issue by xujin-wk** [lsqy/taro-music#142]
我看到你README里的图片地址是https://camo.githubusercontent.com/bcb8dc82043be3e7977bf4f167e5e226d3c68fbdc0c58f30712ebe4b6ba16055/68747470733a2f2f6f7363696d672e6f736368696e612e6e65742f6f73636e65742f34393866646663393863633839643732313936646465643466353461666132396564342e6a7067

域名是githubusercontent.com，怎么才能把图片上传到这个域名下呢，或者怎么能通过这个域名访问图片呢？非常感谢答疑~

**Comment by lsqy** [comment]
@jin522 你在README上面上传图片默认都是在这个域名下的
