### ISSUE TITLE
文件都不全 压根跑都跑不了

### ISSUE THREAD

**Issue by fangkyi03** [lsqy/taro-music#144]
<img width="605" alt="image" src="https://user-images.githubusercontent.com/30390014/173191752-d0013328-1889-4d13-9808-0bb3175282ae.png">
<img width="1376" alt="image" src="https://user-images.githubusercontent.com/30390014/173191768-d3734ee3-e1c6-4671-91d2-4e43169c9891.png">

**Comment by lsqy** [comment]
认真看下`READEME`
![image](https://user-images.githubusercontent.com/18533232/173852377-6ebb4376-fc23-4245-8d84-8cda619d4ec4.png)
