### ISSUE TITLE
 code: 'ERR_UNHANDLED_REJECTION

### ISSUE THREAD

**Issue by wengbenjue** [lsqy/taro-music#147]
@ ./node_modules/taro-ui/dist/weapp/index.ts 3:0-33
 @ ./node_modules/taro-ui/dist/index.js
 @ ./node_modules/babel-loader/lib!./src/pages/my/index.tsx
 @ ./src/pages/my/index.tsx

node:internal/process/promises:246
          triggerUncaughtException(err, true /* fromPromise */);
          ^

[UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "[object Array]".] {
  code: 'ERR_UNHANDLED_REJECTION'
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by lsqy** [comment]
@wbj0110 确认下taro的版本安装是否正确
