### ISSUE TITLE
尝试npm安装，提示依赖包错误

### ISSUE THREAD

**Issue by linjiuqiu** [lsqy/taro-music#148]
**问题描述**

依赖包错误请问要怎么解决,我尝试换了一台电脑，还是报相同的错误
![image](https://user-images.githubusercontent.com/67308950/196730202-fc149258-b50c-427b-b47e-482f9ff56c0b.png)

**复现步骤**

```js
// 这里可以贴代码
```

**期望行为**

**报错信息**

**系统信息**

`Taro CLI 3.3.14 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 16.18.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.19 - C:\Users\linjiuqiu\AppData\Roaming\npm\yarn.CMD
      npm: 8.19.2 - C:\Program Files\nodejs\npm.CMD`

**补充信息**

**Comment by lsqy** [comment]
可以尝试使用`cnpm`来进行下安装 @linjiuqiu

**Comment by linjiuqiu** [comment]
确实可以了，感谢
