### ISSUE TITLE
运行 npm run dev:h5 报错

### ISSUE THREAD

**Issue by curechen** [lsqy/taro-music#151]
**问题描述**
按照readme文档taro版本已经更换成3.3.14，且开启了api接口，测试了一下微信小程序运行是没有问题的，但是当运行h5版本时，控制台显示编译失败，并且页面上只有一个搜索框

**复现步骤**
直接运行 npm run dev:h5

**报错信息**
报错如下
![image](https://user-images.githubusercontent.com/62933321/204526501-71381d46-1eeb-4523-ba26-8ee9a1045966.png)
页面的样子
![image](https://user-images.githubusercontent.com/62933321/204770198-5e1b1667-e851-4595-ba43-792dbe11ebe2.png)

代码
```
./node_modules/_react-redux@7.2.9@react-redux/es/utils/reactBatchedUpdates.js
Module not found: Can't resolve 'react-dom' in 'D:\workplace\taro\taro-music\node_modules\_react-redux@7.2.9@react-redux\es\utils'
```

**系统信息**
👽 Taro v3.3.14

  Taro CLI 3.3.14 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 16.14.0 - D:\nodejs\node.EXE
      Yarn: 1.22.19 - C:\Users\duhai\AppData\Roaming\npm\yarn.CMD
      npm: 8.3.1 - D:\nodejs\npm.CMD

**Comment by lsqy** [comment]
目前这个没有适配H5侧，有兴趣的话可以自行适配下 @curechen
