### ISSUE TITLE
基于Taro v3.3.14运行失败

### ISSUE THREAD

**Issue by nitrohe** [lsqy/taro-music#155]
**问题描述**
基于Taro v3.3.14运行失败

**复现步骤**
下载代码，按照readme文档，安装taro v3.3.14；
创建config.ts文件；
运行npm run dev:weapp报错；

**期望行为**
协助排查一下问题原因；

**报错信息**
编译  发现页面  src/pages/packageA/pages/recentPlay/index.tsx
�   编译失败. 2023/10/2 10:39:06

./node_modules/taro-ui/dist/style/index.scss
Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
SassError: Undefined operation "calc($col / 12) * 100%".
    ╷
120 │     $width: calc($col / 12) * 100%;
    │             ^^^^^^^^^^^^^^^^^^^^^^
    ╵
  node_modules\taro-ui\dist\style\components\flex.scss 120:13  @import
  node_modules\taro-ui\dist\style\components\index.scss 6:9    @import
  node_modules\taro-ui\dist\style\index.scss 12:9              root stylesheet

**系统信息**
� Taro v3.3.14

  Taro CLI 3.3.14 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 16.18.1 - D:\software\nvm\nodejs\node.EXE
      Yarn: 1.22.19 - D:\software\Yarn\bin\yarn.CMD
      npm: 8.19.2 - D:\software\nvm\nodejs\npm.CMD

**补充信息**

**Comment by yinlean** [comment]
+ 1 ， 这个有解决方案吗？

**Comment by niyingg** [comment]
我也是这样 node14 和16 都试过了

**Comment by lsqy** [comment]
@niyingg @nitrohe @yinlean 已更新到taro的最新版本，重新pull下最新项目运行即可
