### ISSUE TITLE
Uncaught Error: module "config" is not defined  你的api.ts里面import的config.js在你的包里没有怎么办？

### ISSUE THREAD

**Issue by caoliren** [lsqy/taro-music#78]

**Comment by lsqy** [comment]
在`README`文档的快速开始部分有说明，首先需要你建一个`config.ts`文件,内容如下：`export const baseUrl: string = 'http://localhost:3000' // 这里配置的这个url是后端服务的请求地址`,你可以根据需要配置成线上地址，这样你就可以在真机上去看效果了 @caoliren
