### ISSUE TITLE
Uncaught TypeError: Cannot read property 'charAt' of undefined

### ISSUE THREAD

**Issue by giantss** [lsqy/taro-music#79]
![image](https://user-images.githubusercontent.com/13778798/70797436-7bca7600-1ddf-11ea-9474-1a2d36ce0912.png)

![image](https://user-images.githubusercontent.com/13778798/70797453-86850b00-1ddf-11ea-87a8-67756d7d49ab.png)

没有跑起来...

**Comment by lsqy** [comment]
这个是因为taro-cli的版本问题导致的，可以参考下[https://github.com/NervJS/taro/issues/4219](https://github.com/NervJS/taro/issues/4219)，以及[taro-cli相关说明](http://taro-docs.jd.com/taro/docs/GETTING-STARTED.html#%E5%B8%B8%E7%94%A8-cli-%E5%91%BD%E4%BB%A4)
可以通过先更新`cli`执行`taro update self`,再更新项目依赖`taro update project`，应该是可以解决你的问题的 @giantss

**Comment by giantss** [comment]
好吧 有空我再看看 我先关闭了 谢谢
