### ISSUE TITLE
 npm run dev:h5 >Failed to compile (Taro v2.1.1)

### ISSUE THREAD

**Issue by tonygshliu** [lsqy/taro-music#98]
🙅   Failed to compile.

./.temp/app.js
Module build failed (from ./node_modules/@tarojs/webpack-runner/node_modules/babel-loader/lib/index.js):
SyntaxError: Unexpected token (126:9)

  124 |         </Provider>;
  125 |   }
> 126 |   config = {
      |          ^
  127 |     pages: ["/pages/index/index", "/pages/dailyRecommend/index", "/pages/my/index", "/pages/videoDetail/index", "/pages/search/index", "/pages/user/index", "/pages/djprogramListDetail/index", "/pages/searchResult/index", "/pages/songDetail/index", "/pages/myFans/index", "/pages/myFocus/index", "/pages/myEvents/index", "/pages/login/index", "/pages/playListDetail/index", "/pages/recentPlay/index"],
  128 |     window: {
  129 |       backgroundTextStyle: 'light',

**Comment by lsqy** [comment]
目前项目中使用的是`2.0.6`版本,你可以执行`taro update project`来将项目中的依赖版本升级成`2.1.1`版本，确保保持一致 @tonygshliu

**Comment by tonygshliu** [comment]
resolved 谢谢。
